# Sanger client vs all servers
alias  ss='./test_sanger.sh --client sanger-cli                              > ./result-sanger-sanger.txt      2>&1 & tail -f ./result-sanger-sanger.txt'
alias ssf='./test_sanger.sh --client sanger-cli --max-references 10 fulltest > ./result-sanger-sanger-full.txt 2>&1 & tail -f ./result-sanger-sanger-full.txt'
alias  sg='./test_google.sh --client sanger-cli                              > ./result-sanger-google.txt      2>&1 & tail -f ./result-sanger-google.txt'
alias sgf='./test_google.sh --client sanger-cli --max-references 10 fulltest > ./result-sanger-google-full.txt 2>&1 & tail -f ./result-sanger-google-full.txt'
alias  se='./test_ena.sh    --client sanger-cli                              > ./result-sanger-ena.txt         2>&1 & tail -f ./result-sanger-ena.txt'
alias sef='./test_ena.sh    --client sanger-cli --max-references 10 fulltest > ./result-sanger-ena-full.txt    2>&1 & tail -f ./result-sanger-ena-full.txt'
alias  sd1='./test_dnanexus_aws.sh    --client sanger-cli                              > ./result-sanger-dnanexus1.txt         2>&1 & tail -f ./result-sanger-dnanexus1.txt'
alias sd1f='./test_dnanexus_aws.sh    --client sanger-cli --max-references 10 fulltest > ./result-sanger-dnanexus1-full.txt    2>&1 & tail -f ./result-sanger-dnanexus1-full.txt'
alias  sd2='./test_dnanexus_azure.sh    --client sanger-cli                              > ./result-sanger-dnanexus2.txt         2>&1 & tail -f ./result-sanger-dnanexus2.txt'
alias sd2f='./test_dnanexus_azure.sh    --client sanger-cli --max-references 10 fulltest > ./result-sanger-dnanexus2-full.txt    2>&1 & tail -f ./result-sanger-dnanexus2-full.txt'

# Dnanexus client vs all servers
alias  ds='./test_sanger.sh --client dnanexus-cli                              > ./result-dnanexus-sanger.txt      2>&1 & tail -f ./result-dnanexus-sanger.txt'
alias dsf='./test_sanger.sh --client dnanexus-cli --max-references 10 fulltest > ./result-dnanexus-sanger-full.txt 2>&1 & tail -f ./result-dnanexus-sanger-full.txt'
alias  dg='./test_google.sh --client dnanexus-cli                              > ./result-dnanexus-google.txt      2>&1 & tail -f ./result-dnanexus-google.txt'
alias dgf='./test_google.sh --client dnanexus-cli --max-references 10 fulltest > ./result-dnanexus-google-full.txt 2>&1 & tail -f ./result-dnanexus-google-full.txt'
alias  de='./test_ena.sh    --client dnanexus-cli                              > ./result-dnanexus-ena.txt         2>&1 & tail -f ./result-dnanexus-ena.txt'
alias def='./test_ena.sh    --client dnanexus-cli --max-references 10 fulltest > ./result-dnanexus-ena-full.txt    2>&1 & tail -f ./result-dnanexus-ena-full.txt'
alias  dd1='./test_dnanexus_aws.sh    --client dnanexus-cli                              > ./result-dnanexus-dnanexus1.txt         2>&1 & tail -f ./result-dnanexus-dnanexus1.txt'
alias dd1f='./test_dnanexus_aws.sh    --client dnanexus-cli --max-references 10 fulltest > ./result-dnanexus-dnanexus1-full.txt    2>&1 & tail -f ./result-dnanexus-dnanexus1-full.txt'
alias  dd2='./test_dnanexus_azure.sh  --client dnanexus-cli                              > ./result-dnanexus-dnanexus2.txt         2>&1 & tail -f ./result-dnanexus-dnanexus2.txt'
alias dd2f='./test_dnanexus_azure.sh  --client dnanexus-cli --max-references 10 fulltest > ./result-dnanexus-dnanexus2-full.txt    2>&1 & tail -f ./result-dnanexus-dnanexus2-full.txt'


# ENA client vs all servers
alias  es='./test_sanger.sh --client ena-cli                              > ./result-ena-sanger.txt      2>&1 & tail -f ./result-ena-sanger.txt'
alias esf='./test_sanger.sh --client ena-cli --max-references 10 fulltest > ./result-ena-sanger-full.txt 2>&1 & tail -f ./result-ena-sanger-full.txt'
alias  eg='./test_google.sh --client ena-cli                              > ./result-ena-google.txt      2>&1 & tail -f ./result-ena-google.txt'
alias egf='./test_google.sh --client ena-cli --max-references 10 fulltest > ./result-ena-google-full.txt 2>&1 & tail -f ./result-ena-google-full.txt'
alias  ee='./test_ena.sh    --client ena-cli                              > ./result-ena-ena.txt         2>&1 & tail -f ./result-ena-ena.txt'
alias eef='./test_ena.sh    --client ena-cli --max-references 10 fulltest > ./result-ena-ena-full.txt    2>&1 & tail -f ./result-ena-ena-full.txt'
alias  ed1='./test_dnanexus_aws.sh    --client ena-cli                              > ./result-ena-dnanexus1.txt         2>&1 & tail -f ./result-ena-dnanexus1.txt'
alias ed1f='./test_dnanexus_aws.sh    --client ena-cli --max-references 10 fulltest > ./result-ena-dnanexus1-full.txt    2>&1 & tail -f ./result-ena-dnanexus1-full.txt'
alias  ed2='./test_dnanexus_azure.sh  --client ena-cli                              > ./result-ena-dnanexus2.txt         2>&1 & tail -f ./result-ena-dnanexus2.txt'
alias ed2f='./test_dnanexus_azure.sh  --client ena-cli --max-references 10 fulltest > ./result-ena-dnanexus2-full.txt    2>&1 & tail -f ./result-ena-dnanexus2-full.txt'

# htsget client vs all servers
alias  hs='./test_sanger.sh 		 --client htsget-cli                              > ./result-htsget-sanger.txt      	2>&1 & tail -f ./result-htsget-sanger.txt'
alias hsf='./test_sanger.sh 		 --client htsget-cli --max-references 10 fulltest > ./result-htsget-sanger-full.txt 	2>&1 & tail -f ./result-htsget-sanger-full.txt'
alias  hg='./test_google.sh 		 --client htsget-cli                              > ./result-htsget-google.txt      	2>&1 & tail -f ./result-htsget-google.txt'
alias hgf='./test_google.sh 		 --client htsget-cli --max-references 10 fulltest > ./result-htsget-google-full.txt 	2>&1 & tail -f ./result-htsget-google-full.txt'
alias  he='./test_ena.sh    		 --client htsget-cli                              > ./result-htsget-ena.txt         	2>&1 & tail -f ./result-htsget-ena.txt'
alias hef='./test_ena.sh    		 --client htsget-cli --max-references 10 fulltest > ./result-htsget-ena-full.txt    	2>&1 & tail -f ./result-htsget-ena-full.txt'
alias  hd1='./test_dnanexus_aws.sh   --client htsget-cli                              > ./result-htsget-dnanexus1.txt       2>&1 & tail -f ./result-htsget-dnanexus1.txt'
alias hd1f='./test_dnanexus_aws.sh   --client htsget-cli --max-references 10 fulltest > ./result-htsget-dnanexus1-full.txt  2>&1 & tail -f ./result-htsget-dnanexus1-full.txt'
alias  hd2='./test_dnanexus_azure.sh --client htsget-cli                              > ./result-htsget-dnanexus2.txt       2>&1 & tail -f ./result-htsget-dnanexus2.txt'
alias hd2f='./test_dnanexus_azure.sh --client htsget-cli --max-references 10 fulltest > ./result-htsget-dnanexus2-full.txt  2>&1 & tail -f ./result-htsget-dnanexus2-full.txt'
