# htsget client vs all servers
alias  hs='./test_sanger.sh             --client htsget-cli                              2>&1 	| tee -i ./result-htsget-sanger.txt          '
alias hsf='./test_sanger.sh             --client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-sanger-full.txt     '
alias  hg='./test_google.sh             --client htsget-cli                              2>&1 	| tee -i ./result-htsget-google.txt          '
alias hgf='./test_google.sh             --client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-google-full.txt     '
alias  he='./test_ena.sh                --client htsget-cli                              2>&1 	| tee -i ./result-htsget-ena.txt             '
alias hef='./test_ena.sh                --client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-ena-full.txt        '
alias  ha='./test_ega.sh                --client htsget-cli                              2>&1 	| tee -i ./result-htsget-ega.txt             '
alias haf='./test_ega.sh                --client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-ega-full.txt        '
alias  hd1='./test_dnanexus_aws.sh  	--client htsget-cli                              2>&1 	| tee -i ./result-htsget-dnanexus1.txt       '
alias hd1f='./test_dnanexus_aws.sh  	--client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-dnanexus1-full.txt  '
alias  hd2='./test_dnanexus_azure.sh	--client htsget-cli                              2>&1 	| tee -i ./result-htsget-dnanexus2.txt       '
alias hd2f='./test_dnanexus_azure.sh	--client htsget-cli --max-references 10 fulltest 2>&1 	| tee -i ./result-htsget-dnanexus2-full.txt  '

# Dnanexus client vs all servers
alias  ds='./test_sanger.sh				--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-sanger.txt     		'
alias dsf='./test_sanger.sh				--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-sanger-full.txt		'
alias  dg='./test_google.sh				--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-google.txt     		'
alias dgf='./test_google.sh				--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-google-full.txt		'
alias  de='./test_ena.sh   				--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-ena.txt        		'
alias def='./test_ena.sh   				--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-ena-full.txt   		'
alias  da='./test_ega.sh   				--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-ega.txt        		'
alias daf='./test_ega.sh   				--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-ega-full.txt   		'
alias  dd1='./test_dnanexus_aws.sh   	--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-dnanexus1.txt     	'
alias dd1f='./test_dnanexus_aws.sh   	--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-dnanexus1-full.txt	'
alias  dd2='./test_dnanexus_azure.sh 	--client dnanexus-cli                              2>&1 | tee -i ./result-dnanexus-dnanexus2.txt     	'
alias dd2f='./test_dnanexus_azure.sh 	--client dnanexus-cli --max-references 10 fulltest 2>&1 | tee -i ./result-dnanexus-dnanexus2-full.txt	'

# Sanger client vs all servers
alias  ss='./test_sanger.sh 			--client sanger-cli                              2>&1 | tee -i ./result-sanger-sanger.txt     		'
alias ssf='./test_sanger.sh 			--client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-sanger-full.txt		'
alias  sg='./test_google.sh 			--client sanger-cli                              2>&1 | tee -i ./result-sanger-google.txt     		'
alias sgf='./test_google.sh 			--client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-google-full.txt		'
alias  se='./test_ena.sh    			--client sanger-cli                              2>&1 | tee -i ./result-sanger-ena.txt        		'
alias sef='./test_ena.sh    			--client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-ena-full.txt   		'
alias  sa='./test_ega.sh    			--client sanger-cli                              2>&1 | tee -i ./result-sanger-ega.txt        		'
alias saf='./test_ega.sh    			--client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-ega-full.txt   		'
alias  sd1='./test_dnanexus_aws.sh   	--client sanger-cli                              2>&1 | tee -i ./result-sanger-dnanexus1.txt     	'
alias sd1f='./test_dnanexus_aws.sh    	--client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-dnanexus1-full.txt	'
alias  sd2='./test_dnanexus_azure.sh    --client sanger-cli                              2>&1 | tee -i ./result-sanger-dnanexus2.txt     	'
alias sd2f='./test_dnanexus_azure.sh    --client sanger-cli --max-references 10 fulltest 2>&1 | tee -i ./result-sanger-dnanexus2-full.txt	'

# ENA client vs all servers
alias  es='./test_sanger.sh				--client ena-cli                              2>&1 | tee -i ./result-ena-sanger.txt     	'
alias esf='./test_sanger.sh				--client ena-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ena-sanger-full.txt	'
alias  eg='./test_google.sh				--client ena-cli                              2>&1 | tee -i ./result-ena-google.txt     	'
alias egf='./test_google.sh				--client ena-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ena-google-full.txt	'
alias  ee='./test_ena.sh   				--client ena-cli                              2>&1 | tee -i ./result-ena-ena.txt        	'
alias eef='./test_ena.sh   				--client ena-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ena-ena-full.txt   	'
alias  ed1='./test_dnanexus_aws.sh  	--client ena-cli                              2>&1 | tee -i ./result-ena-dnanexus1.txt      '
alias ed1f='./test_dnanexus_aws.sh  	--client ena-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ena-dnanexus1-full.txt '
alias  ed2='./test_dnanexus_azure.sh	--client ena-cli                              2>&1 | tee -i ./result-ena-dnanexus2.txt      '
alias ed2f='./test_dnanexus_azure.sh	--client ena-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ena-dnanexus2-full.txt '

# samtools client vs all servers
alias  ts='./test_sanger.sh             --client samtools-cli                              2>&1 | tee -i ./result-samtools-sanger.txt          '
alias tsf='./test_sanger.sh             --client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-sanger-full.txt     '
alias  tg='./test_google.sh             --client samtools-cli                              2>&1 | tee -i ./result-samtools-google.txt          '
alias tgf='./test_google.sh             --client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-google-full.txt     '
alias  te='./test_ena.sh                --client samtools-cli                              2>&1 | tee -i ./result-samtools-ena.txt             '
alias tef='./test_ena.sh                --client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-ena-full.txt        '
alias  ta='./test_ega.sh                --client samtools-cli                              2>&1 | tee -i ./result-samtools-ega.txt             '
alias taf='./test_ega.sh                --client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-ega-full.txt        '
alias  td1='./test_dnanexus_aws.sh  	--client samtools-cli                              2>&1 | tee -i ./result-samtools-dnanexus1.txt       '
alias td1f='./test_dnanexus_aws.sh  	--client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-dnanexus1-full.txt  '
alias  td2='./test_dnanexus_azure.sh	--client samtools-cli                              2>&1 | tee -i ./result-samtools-dnanexus2.txt       '
alias td2f='./test_dnanexus_azure.sh	--client samtools-cli --max-references 10 fulltest 2>&1 | tee -i ./result-samtools-dnanexus2-full.txt  '

# EGA client vs all servers
alias  as='./test_sanger.sh				--client ega-cli                              2>&1 | tee -i ./result-ega-sanger.txt     	'
alias asf='./test_sanger.sh				--client ega-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ega-sanger-full.txt	'
alias  ag='./test_google.sh				--client ega-cli                              2>&1 | tee -i ./result-ega-google.txt     	'
alias agf='./test_google.sh				--client ega-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ega-google-full.txt	'
alias  aa='./test_ega.sh   				--client ega-cli                              2>&1 | tee -i ./result-ega-ega.txt        	'
alias aaf='./test_ega.sh   				--client ega-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ega-ega-full.txt   	'
alias  ad1='./test_dnanexus_aws.sh  	--client ega-cli                              2>&1 | tee -i ./result-ega-dnanexus1.txt      '
alias ad1f='./test_dnanexus_aws.sh  	--client ega-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ega-dnanexus1-full.txt '
alias  ad2='./test_dnanexus_azure.sh	--client ega-cli                              2>&1 | tee -i ./result-ega-dnanexus2.txt      '
alias ad2f='./test_dnanexus_azure.sh	--client ega-cli --max-references 10 fulltest 2>&1 | tee -i ./result-ega-dnanexus2-full.txt '
